# Generated by Django 4.1.1 on 2022-09-21 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auxiliar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_aux', models.CharField(max_length=30, verbose_name='Nombre_aux')),
                ('apel_aux', models.CharField(max_length=30, verbose_name='Apel_aux')),
                ('direc_aux', models.CharField(max_length=30, verbose_name='Direc_aux')),
            ],
        ),
    ]
